version: "3.7"

volumes:
  postgres:

services:
  # [START app_services]
  express:
    build: .
    image: express_app
    command: >
      bash -c "npm run migrate &&
               npm run start"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=qwerty
      - PASSWORD_SALT=10
      - JWT_SECURITY_PASSWORD=Hw5Czc7zjwyjRC8ze7Su1UoE4Lnm
    ports:
      - 3000:3000
    volumes:
      - .env:/code/.env
    depends_on:
      - postgres
  # [END app_services]

  # [START db_services]
  postgres:
    container_name: postgres_bitcoin
    image: debezium/postgres:11-alpine
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: qwerty
  # [END db_services]